name: corsac_jwt
version: 0.1.0-dev
description: Lightweight implementation of JSON Web Tokens (JWT)
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: ">=1.16.0 <2.0.0"

dependencies:
  logging: "^0.11.3"
  pointycastle: "^0.10.0"
  rsa_pkcs: "^0.1.2"
  crypto: "^2.0.0"

dev_dependencies:
  test: "^0.12.6+1"
