name: corsac_jwt
version: 0.1.0-dev
description: Lightweight implementation of JSON Web Tokens (JWT)
homepage: https://github.com/corsac-dart/jwt
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: "^0.12.6+1"
  dart_coveralls: "^0.4.0"
